name: Unzip File

on:
  workflow_dispatch:  # Allows manual trigger of this action

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unzip file
      run: unzip <awesome-oss-alternatives-main.zip> -d <landing-page>

    - name: Commit unzipped files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Unzipped files"
        git push
